FROM arm64v8/maven:3.6-amazoncorretto-8 AS build
MAINTAINER maximilian schiedermeier
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -P docker-dev

## Discard Maven, run JAR file using JRE
FROM openjdk:8-jre-alpine

# copy the jar from the build stage, expose the required port and run it.
COPY --from=build /usr/src/app/target/ls.jar /usr/app/ls.jar
EXPOSE 4242

ENTRYPOINT ["java", "-jar", "/usr/app/ls.jar"]